### ISSUE TITLE
[AsciiDoc] Remove image `max-height`

### ISSUE THREAD

**Issue by benjaminleonard** [oxidecomputer/design-system#58]
This causes an image to stretch (which can be fixed with `object-fit: contain` but I think it's presence causes more issues than it solves. We should just be mindful in the images that we use in our documents.

https://github.com/oxidecomputer/design-system/blob/e4cd45eb467e7217c2b69ab87bad92325d643c86/components/src/assets/asciidoc.css#L37

**Comment by zephraph** [comment]
:rocket: Issue was released in [`v1.2.11`](https://github.com/oxidecomputer/design-system/releases/tag/v1.2.11) :rocket:
