### ISSUE TITLE
Could use a font size between xl and 2xl

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/design-system#84]
### `text-sans-2xl` is too big

<img width="510" alt="image" src="https://github.com/user-attachments/assets/5eee1861-1763-4181-ba45-c7f7f74d98af">

### `text-sans-xl` is too small

<img width="510" alt="image" src="https://github.com/user-attachments/assets/c6d92e03-eb41-4595-b55d-ed36ed1daedd">

**Comment by benjaminleonard** [comment]
Solved through the magic of _graphic design_.
